controller_list:
  - name: fake_left_manipulator_controller
    joints:
      - left_iiwa_arm_joint_1
      - left_iiwa_arm_joint_2
      - left_iiwa_arm_joint_3
      - left_iiwa_arm_joint_4
      - left_iiwa_arm_joint_5
      - left_iiwa_arm_joint_6
      - left_iiwa_arm_joint_7
  - name: fake_right_manipulator_controller
    joints:
      - right_iiwa_arm_joint_1
      - right_iiwa_arm_joint_2
      - right_iiwa_arm_joint_3
      - right_iiwa_arm_joint_4
      - right_iiwa_arm_joint_5
      - right_iiwa_arm_joint_6
      - right_iiwa_arm_joint_7
initial:  # Define initial robot poses.
  - group: left_manipulator
    pose: vertical
  - group: right_manipulator
    pose: vertical