controller_list:
  - name: iiwa/PositionJointInterface_left_trajectory_controller
    action_ns: left_follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_iiwa_arm_joint_1
      - left_iiwa_arm_joint_2
      - left_iiwa_arm_joint_3
      - left_iiwa_arm_joint_4
      - left_iiwa_arm_joint_5
      - left_iiwa_arm_joint_6
      - left_iiwa_arm_joint_7
  - name: iiwa/PositionJointInterface_right_trajectory_controller
    action_ns: right_follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_iiwa_arm_joint_1
      - right_iiwa_arm_joint_2
      - right_iiwa_arm_joint_3
      - right_iiwa_arm_joint_4
      - right_iiwa_arm_joint_5
      - right_iiwa_arm_joint_6
      - right_iiwa_arm_joint_7
